import { AlbumCardSetupEntry } from "../types";

export const AlbumCardSetup: AlbumCardSetupEntry[] = [
  {
    title: "The College Dropout",
    tracks: "?",
    year: 2004,
    cover: "../../images/the-college-dropout.jpg",
    alt: "",
  },
  {
    title: "Late Registration",
    tracks: "?",
    year: 2005,
    cover: "../../images/late-registration.jpg",
    alt: "",
  },
  {
    title: "Graduation",
    tracks: "15",
    year: 2007,
    cover: "../../images/graduation.jpeg",
    alt: "Graduation",
  },
  {
    title: "808s & Heartbreak",
    tracks: "?",
    year: 2008,
    cover: "../../images/808s-&-heartbreak.png",
    alt: "",
  },
  {
    title: "My Beautiful Dark Twisted Fantasy",
    tracks: "?",
    year: 2010,
    cover: "../../images/my-beautiful-dark-twisted-fantasy.jpg",
    alt: "",
  },
  {
    title: "Watch the Throne",
    tracks: "?",
    year: 2011,
    cover: "../../images/watch-the-throne.jpg",
    alt: "",
  },
  {
    title: "Yeezus",
    tracks: "?",
    year: 2013,
    cover: "../../images/yeezus.png",
    alt: "",
  },
  {
    title: "The Life of Pablo",
    tracks: "?",
    year: 2016,
    cover: "../../images/the-life-of-pablo.jpg",
    alt: "",
  },
  {
    title: "Ye",
    tracks: "?",
    year: 2018,
    cover: "../../images/ye.jpg",
    alt: "Ye",
  },
  {
    title: "Kids See Ghosts",
    tracks: "?",
    year: 2018,
    cover: "../../images/kids-see-ghosts.png",
    alt: "",
  },
  {
    title: "Jesus is King",
    tracks: "?",
    year: 2019,
    cover: "../../images/jesus-is-king.png",
    alt: "",
  },
  {
    title: "Jesus is Born",
    tracks: "?",
    year: 2019,
    cover: "../../images/jesus-is-born.png",
    alt: "",
  },
  {
    title: "Donda",
    tracks: "?",
    year: 2021,
    cover: "../../images/donda.jpeg",
    alt: "",
  },
  {
    title: "Donda 2",
    tracks: "?",
    year: 2022,
    cover: "../../images/donda-2.jpg",
    alt: "",
  },
  {
    title: "Vultures",
    tracks: "?",
    year: 2023,
    cover: "../../images/vultures.png",
    alt: "",
  }
  ];
  
  // {
  //   title: "",
  //   tracks: "?",
  //   year: 20,
  //   cover: "../../images/.jpeg",
  //   alt: "",
  // },